In [ ]:
!unzip /content/train.zip
!unzip /content/test.zip

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import cv2
from google.colab.patches import cv2_imshow
import numpy as np
import os
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix


In [ ]:
labels_train = []
labels_test = []
train_image_vectors = []  # Her kategori için ayrı bir liste oluştur
test_image_vectors = []   # Her kategori için ayrı bir liste oluştur

classes_name = {'Motorbikes' : 0,
                'cellphone' : 1,
                'flamingo' : 2}

for category, label in classes_name.items():
    print(label)
    print(category)
    train_category_folder = os.path.join('train', category)
    test_category_folder = os.path.join('test', category)

    train_image_paths = []
    for filename in os.listdir(train_category_folder):
        labels_train.append(category)
        path = os.path.join(train_category_folder, filename)
        train_image_paths.append(path)

    test_image_paths = []
    for filename in os.listdir(test_category_folder):
        labels_test.append(category)
        path = os.path.join(test_category_folder, filename)
        test_image_paths.append(path)

    for train_image_path in train_image_paths:
        train_image = cv2.imread(train_image_path)
        train_image = cv2.resize(train_image, (128,128))
        train_grayscale_image = cv2.cvtColor(train_image, cv2.COLOR_BGR2GRAY)

        gradient_x = cv2.Sobel(train_grayscale_image, cv2.CV_64F, 1, 0, ksize=5)
        gradient_y = cv2.Sobel(train_grayscale_image, cv2.CV_64F, 0, 1, ksize=5)
        gradient_magnitude = np.sqrt(gradient_x**2 + gradient_y**2)

        train_vector = gradient_magnitude.flatten().astype(np.float16).reshape((1,-1))
        train_image_vectors.append(train_vector)

    for test_image_path in test_image_paths:
        test_image = cv2.imread(test_image_path)
        test_image = cv2.resize(test_image, (128,128))
        test_grayscale_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2GRAY)

        gradient_x = cv2.Sobel(test_grayscale_image, cv2.CV_64F, 1, 0, ksize=5)
        gradient_y = cv2.Sobel(test_grayscale_image, cv2.CV_64F, 0, 1, ksize=5)
        gradient_magnitude = np.sqrt(gradient_x**2 + gradient_y**2)

        test_vector = gradient_magnitude.flatten().astype(np.float16).reshape((1,-1))
        test_image_vectors.append(test_vector)

train_image_vectors = np.array(train_image_vectors)
test_image_vectors = np.array(test_image_vectors)

print(train_image_vectors)
print(train_image_vectors.shape)

print(test_image_vectors)
print(test_image_vectors.shape)

print(labels_train)

0
Motorbikes
1
cellphone
2
flamingo
[[[   0.    0.    0. ...    0.    0.    0.]]

 [[   0.    0.    0. ...    0.    0.    0.]]

 [[   0.    0.    0. ...    0.    0.    0.]]

 ...

 [[   0. 1512. 1952. ... 1680. 1536.    0.]]

 [[   0.  264.  226. ...  122.   46.    0.]]

 [[   0.    6.   30. ...    0.    0.    0.]]]
(294, 1, 16384)
[[[   0.    0.    0. ...    0.    0.    0.]]

 [[   0.   78.   10. ...  132.  214.    0.]]

 [[   0.    0.    0. ...    0.    0.    0.]]

 ...

 [[   0.  480.  382. ... 7272. 3182.    0.]]

 [[   0.    0.    0. ...    0.    0.    0.]]

 [[   0. 1070. 2842. ...  286.  320.    0.]]]
(96, 1, 16384)
['Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Mot

In [ ]:
from sklearn.metrics.pairwise import manhattan_distances, euclidean_distances

def KNN(x_train, y_train, sample_test, k):  # x_train -> train verileri y_train -> sınıflar sample_test -> test verileri
  knn = KNeighborsClassifier(n_neighbors = k) # default k = 5

  knn.fit(x_train, y_train)

  predicted_class = knn.predict(sample_test)

  return predicted_class

In [ ]:
combined_train_data = list(zip(train_image_vectors, labels_train))
combined_test_data = list(zip(test_image_vectors, labels_test))

np.random.shuffle(combined_train_data)
np.random.shuffle(combined_test_data)

train_data, train_labels = zip(*combined_train_data)
test_data, test_labels = zip(*combined_test_data)

train_data = np.array(train_data)
test_data = np.array(test_data)

train_labels = list(train_labels)
test_labels = list(test_labels)


print(train_data.shape)
print(test_data.shape)
print(train_labels)
print(test_labels)

(294, 1, 16384)
(96, 1, 16384)
['flamingo', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'flamingo', 'flamingo', 'Motorbikes', 'Motorbikes', 'cellphone', 'flamingo', 'Motorbikes', 'Motorbikes', 'cellphone', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'flamingo', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'cellphone', 'Motorbikes', 'cellphone', 'Motorbikes', 'flamingo', 'Motorbikes', 'cellphone', 'flamingo', 'Motorbikes', 'Motorbikes', 'cellphone', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'cellphone', 'cellphone', 'cellphone', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'flamingo', 'flamingo', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'cellphone', 'flamingo', 'flamingo', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'Motorbikes', 'flamingo', 'Motorbikes', 'cellphone', 'flamingo', 'Motorbikes', 'Motorbikes', 'cellphone', 'flamingo', 'Motorbikes', 'Motorbikes', 'flamingo', 'c

In [ ]:
x_train = train_data[:,0,:]
y_train = np.array(train_labels).reshape(-1,1)
sample_test = test_data[:,0,:]

print(x_train.shape)
print(y_train.shape)
print(type(y_train))
print(sample_test.shape)


(294, 16384)
(294, 1)
<class 'numpy.ndarray'>
(96, 16384)


In [ ]:
# Euclidean
predictions = KNN(x_train, y_train, sample_test, k = 5)
accuracy = accuracy_score(labels_test, predictions)
conf = confusion_matrix(labels_test, predictions)

print(conf)
print(accuracy)

[[61  4 16]
 [ 5  1  1]
 [ 7  0  1]]
0.65625


In [ ]:
# manhattan
predictions = KNN(x_train, y_train, sample_test, k = 5)
accuracy = accuracy_score(labels_test, predictions)
conf = confusion_matrix(labels_test, predictions)

print(conf)
print(accuracy)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


[[55  1 25]
 [ 5  1  1]
 [ 7  0  1]]
0.59375


In [ ]:
# cosine
predictions = KNN(x_train, y_train, sample_test, k = 5)
accuracy = accuracy_score(labels_test, predictions)
conf = confusion_matrix(labels_test, predictions)

print(conf)
print(accuracy)

[[71  4  6]
 [ 5  2  0]
 [ 7  0  1]]
0.7708333333333334


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [ ]:
# default

predictions = KNN(x_train, y_train, sample_test, k = 5)
accuracy = accuracy_score(labels_test, predictions)
conf = confusion_matrix(labels_test, predictions)

print(conf)
print(accuracy)

[[61  4 16]
 [ 5  1  1]
 [ 7  0  1]]
0.65625


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
